routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/', 'HomeController@aboutMe')->name('welcome');

Route::group(['middleware'=>'auth'], function(){
 //   Route::get('admin', function(){
 //   return view ('admin.dashboard');
	// });
   	//Route::resource('admin','AdminController');
   	Route::get('admin','AdminController@index')->name('dashboard');
	Route::resource('admin/abouts','AboutController');
	Route::resource('admin/skills','SkillController');
	Route::resource('admin/educations','EducationController');
	Route::resource('admin/experiences','ExperienceController');
	Route::resource('admin/portfolios','PortfolioController');
	Route::resource('admin/testimonials','TestimonialController');
	Route::resource('admin/contacts','ContactController');
});

Route::get('/', 'FrontController@getComplateResume');
Route::post('/', 'FrontController@saveContact')->name('contacts');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Education.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    //
}

app/Http/Controllers/EducationController.php
<?php

namespace App\Http\Controllers;

use App\Education;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class EducationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $educations = Education::all();
        return view('admin.educations.index',compact(['educations']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.educations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $education = new Education;

        $this->validate($request,[
          'inistitute_name' => 'required|max:150',
          'board_name' => 'required|max:100',
          'certificate' => 'required|max:100',
          'result' => 'required|max:100',
          'session' => 'required|max:100',
        ],[
          'inistitute_name.required' => ' Inistitute name field is required.',
          'inistitute_name.max' => ' Inistitute name may not be greater than 150 characters.',
          'board_name.required' => ' Board name field is required.',
          'board_name.max' => ' Board name may not be greater than 100 characters.',
          'certificate.required' => ' Certificate name field is required.',
          'certificate.max' => ' Certificate name may not be greater than 100 characters.',
          'result.required' => ' Result field is required.',
          'result.max' => ' Result may not be greater than 100 characters.',
          'session.required' => ' Session name field is required.',
          'session.max' => ' Session name may not be greater than 150 characters.',
        ]);

        $education->inistitute_name = $request->input('inistitute_name');
        $education->board_name = $request->input('board_name');
        $education->certificate = $request->input('certificate');
        $education->result = $request->input('result');
        $education->session = $request->input('session');

        Session::flash('success','Education Successfully Added');

        
        $education->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function show(Education $education)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function edit(Education $education)
    {
        return view('admin.educations.edit',compact(['education']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Education $education)
    {
        $this->validate($request,[
          'inistitute_name' => 'required|max:150',
          'board_name' => 'required|max:100',
          'certificate' => 'required|max:100',
          'result' => 'required|max:100',
          'session' => 'required|max:100',
        ],[
          'inistitute_name.required' => ' Inistitute name field is required.',
          'inistitute_name.max' => ' Inistitute name may not be greater than 150 characters.',
          'board_name.required' => ' Board name field is required.',
          'board_name.max' => ' Board name may not be greater than 100 characters.',
          'certificate.required' => ' Certificate name field is required.',
          'certificate.max' => ' Certificate name may not be greater than 100 characters.',
          'result.required' => ' Result field is required.',
          'result.max' => ' Result may not be greater than 100 characters.',
          'session.required' => ' Session name field is required.',
          'session.max' => ' Session name may not be greater than 150 characters.',
        ]);

        $education->inistitute_name = $request->input('inistitute_name');
        $education->board_name = $request->input('board_name');
        $education->certificate = $request->input('certificate');
        $education->result = $request->input('result');
        $education->session = $request->input('session');

        Session::flash('update','Education Successfully Updated');
        
        $education->save();

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function destroy(Education $education)
    {
        $education->delete();
        Session::flash('delete','Education Successfully delete');
        return redirect()->back();
    }
}

resources/views/admin/educations/create.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">Add Education Details</h4>
                    </div>
                    <div class="card-body"> 
                        @if ($message = Session::get('success'))
                        <div class="alert alert-info alert-block">
                           <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if(count($errors))
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <br/>
                                <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('educations.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-body">
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Inistitute Name</label>
                                            <input type="text" id="inistitute_name" name="inistitute_name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Board Name</label>
                                            <input type="text" id="board_name" name="board_name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Certificate</label>
                                            <input type="text" id="cartificate" name="certificate" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Result</label>
                                            <input type="text" id="result" name="result" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Session</label>
                                            <input type="text" id="Session" name="session" class="form-control">
                                        </div>
                                       
                                    </div>
                                   
                                </div>
                        
                           
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                <a role="button" class="btn btn-inverse" href="{{ route('educations.index') }}">Cancel</a>
                                
                            </div>
                        </form>
                             
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 

resources/views/admin/educations/edit.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">Add Education Details</h4>
                    </div>
                    <div class="card-body"> 
                        @if ($message = Session::get('update'))
                        <div class="alert alert-info alert-block">
                           <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if(count($errors))
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <br/>
                                <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('educations.update',['education'=>$education->id]) }}" method="post">
                            {{ csrf_field() }}{{ method_field('PATCH') }}
                            <div class="form-body">
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Inistitute Name</label>
                                            <input type="text" id="inistitute_name" name="inistitute_name" class="form-control" value="{{ $education->inistitute_name }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Board Name</label>
                                            <input type="text" id="board_name" name="board_name" class="form-control" value="{{ $education->board_name }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Certificate</label>
                                            <input type="text" id="cartificate" name="certificate" class="form-control" value="{{ $education->certificate }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Result</label>
                                            <input type="text" id="result" name="result" class="form-control" value="{{ $education->result }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Session</label>
                                            <input type="text" id="Session" name="session" class="form-control" value="{{ $education->session }}">
                                        </div>
                                       
                                    </div>
                                   
                                </div>
                        
                           
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Update</button>
                                <a role="button" class="btn btn-inverse" href="{{ route('educations.index') }}">Cancel</a>
                                
                            </div>
                        </form>
                             
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 

resources/views/admin/educations/index.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                        <h1 class="card-title">Education Details
                        <a class="btn btn-primary pull-right" href="{{ route('educations.create') }}" type="button">Add Education</a>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="table-responsive">
                            @if ($message = Session::get('delete'))
                            <div class="alert alert-danger alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                            </div>
                            @endif
                            <table class="table">
                                <thead>
                                    <tr>
                                      <th>#</th>
                                      <th width="20%">Inistitute Name</th>
                                      <th width="15%">Board Name</th>
                                      <th width="25%">Certificate</th>
                                      <th width="20%">Result</th>
                                      <th width="20%">Session</th>
                                      <th>Edit</th>
                                      <th>Delete</th>
                                    </tr>
                                </thead>
                                @if($educations)
                                <tbody>
                                    @foreach($educations as $key=>$education)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td>{{ $education->inistitute_name }}</td>
                                        <td>{{ $education->board_name }}</td>
                                        <td>{{ $education->certificate }}</td>
                                        <td>{{ $education->result }}</td>
                                        <td>{{ $education->session }}</td>
                                        <td>
                                            <a role="button" href="{{ route('educations.edit',['education' => $education->id]) }}"><i class="fa fa-edit icon-size"></i></i></a>

                                        </td>
                                        <td>
                                            
                                            <form action="{{ route('educations.destroy',['education'=>$education->id]) }}" method="post">
                                                {{ csrf_field() }}{{ method_field('DELETE') }}
                                                <button role="link" class="fa fa-trash icon-size" type="submit"></button>
                                            </form>
                                        </td>
                                    </tr>   
                                    @endforeach                                             
                                </tbody>
                                @endif
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 