routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/', 'HomeController@aboutMe')->name('welcome');

Route::group(['middleware'=>'auth'], function(){
 //   Route::get('admin', function(){
 //   return view ('admin.dashboard');
	// });
   	//Route::resource('admin','AdminController');
   	Route::get('admin','AdminController@index')->name('dashboard');
	Route::resource('admin/abouts','AboutController');
	Route::resource('admin/skills','SkillController');
	Route::resource('admin/educations','EducationController');
	Route::resource('admin/experiences','ExperienceController');
	Route::resource('admin/portfolios','PortfolioController');
	Route::resource('admin/testimonials','TestimonialController');
	Route::resource('admin/contacts','ContactController');
});

Route::get('/', 'FrontController@getComplateResume');
Route::post('/', 'FrontController@saveContact')->name('contacts');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    //
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Skill;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class SkillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = Skill::all();
        return view('admin.skills.index', compact(['skills']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $skill = new Skill;


        $this->validate($request,[
          'name' => 'required|unique:skills|max:100',
          'progress' => 'required',
        ],[
          'name.required' => ' Skill field is required.',
          'title.max' => ' Skill may not be greater than 100 characters.',
          'title.unique' => ' Skill already exist',
          'progress.required' => ' Progress field is required.',
        ]);

        $skill->name = $request->input('name');
        $skill->progress = $request->input('progress');

        Session::flash('success','Skill Successfully Added');

        $skill->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function show(Skill $skill)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function edit(Skill $skill)
    {
        $skills = Skill::all();
        return view('admin.skills.edit',compact(['skill','skills']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Skill $skill)
    {
        $this->validate($request,[
          'name' => 'required|unique:skills|max:100',
          'progress' => 'required',
        ],[
          'name.required' => ' Skill field is required.',
          'title.max' => ' Skill may not be greater than 100 characters.',
          'title.unique' => ' Skill already exist',
          'progress.required' => ' Progress field is required.',
        ]);

        $skill->name = $request->input('name');
        $skill->progress = $request->input('progress');

        Session::flash('update','Skill Successfully Updated');

        $skill->save();

        return redirect('admin/skils');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function destroy(Skill $skill)
    {
        $skill->delete();
        Session::flash('delete','Skill Successfully delete');
        return redirect()->back();
    }
}

resources/views/admin/skills/edit.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                       <h1 class="card-title">Skills</h1>                  
                      	<!-- Start Page Content -->
                      	<div class="row">
                      	    <div class="col-lg-6">
                      	        <div class="card card-outline-primary">
                      	            <div class="card-header">
                      	                <h4 class="m-b-0 text-white">Edit Skill</h4>
                      	            </div>
                      	            <div class="card-body">
                                      @if ($message = Session::get('update'))
                                      <div class="alert alert-info alert-block">
                                         <button type="button" class="close" data-dismiss="alert">×</button> 
                                              <strong>{{ $message }}</strong>
                                      </div>
                                      @endif

                                       @if(count($errors))
                                           <div class="alert alert-danger">
                                             <strong>Whoops!</strong> There were some problems with your input.
                                             <br/>
                                             <ul>
                                               @foreach($errors->all() as $error)
                                               <li>{{ $error }}</li>
                                               @endforeach
                                             </ul>
                                           </div>
                                         @endif
                      	                <form action="{{ route('skills.update',['skill' => $skill->id]) }}" method="post">
                      	                	{{ csrf_field() }}{{ method_field('PATCH') }}
                      	                    <div class="form-body">
                      	                        <div class="row p-t-20">
                      	                            <div class="col-md-12">
                      	                                <div class="form-group">
                      	                                    <label class="control-label">Your Skill</label>
                      	                                    <input type="text" id="name" name="name" class="form-control" value="{{ $skill->name }}">
                      	                                </div>
                                                        <div class="form-group">
                                                            <label class="control-label">Skill progress</label>
                                                            <input type="text" id="progress" name="progress" value="{{ $skill->progress }}" class="form-control">
                                                        </div>
                      	                            </div>
                      	                           
                      	                        </div>
                      	             
                      	                   
                      	                    </div>
                      	                    <div class="form-actions">
                      	                        <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Update</button>
                                                <a role="button" class="btn btn-inverse" href="{{ route('skills.index') }}">Cancel</a>
                      	                        
                      	                    </div>
                      	                </form>
                      	            </div>
                      	        </div>
                      	    </div>
                      		

                      		<div class="col-lg-6">
                      	        <div class="card card-outline-info">
                      	            <div class="card-header">
                      	                <h4 class="m-b-0 text-white">List of Skills</h4>
                      	            </div>
                      	            <div class="card-body">
                                      @if ($message = Session::get('delete'))
                                      <div class="alert alert-danger alert-block">
                                        <button type="button" class="close" data-dismiss="alert">×</button> 
                                        <strong>{{ $message }}</strong>
                                      </div>
                                      @endif
                      	                <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                      <th>#</th>
                                                      <th>Skill</th>
                                                      <th>Progress</th>
                                                      <th>Edit</th>
                                                      <th>Delete</th>
                                                    </tr>
                                                </thead>
                                                @if($skills)
                                                <tbody>
                                                	@foreach($skills as $key=>$skill)
                                                    <tr>
                                                    	<td>{{ ++$key }}</td>
                                                    	<td>{{ $skill->name }}</td>
                                                      <td>{{ $skill->progress }}</td>
                                                    	<td>
                                                    		<a href="{{ route('skills.edit',['skill' => $skill->id]) }}"><i class="fa fa-edit icon-size"></i></a>
                                                    	</td>
                                                      <td>
                                                        <form action="{{ route('skills.destroy',['skill' => $skill->id]) }}" method="post">
                                                          {{ csrf_field() }}{{ method_field('DELETE') }}
                                                          <button role="link" class="fa fa-trash icon-size" type="submit"></button>
                                                        </form>
                                                      </td>
                                                    </tr>   
                                                    @endforeach                                             
                                                </tbody>
                                                @endif
                                            </table>
                                        </div>
                      	            </div>
                      	        </div>
                      	    </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 

resources/views/admin/skills/index.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                       <h1 class="card-title">Skills</h1>                  
                      	<!-- Start Page Content -->
                      	<div class="row">
                      	    <div class="col-lg-6">
                      	        <div class="card card-outline-primary">
                      	            <div class="card-header">
                      	                <h4 class="m-b-0 text-white">Add New Skill</h4>
                      	            </div>
                      	            <div class="card-body">
                                      @if ($message = Session::get('success'))
                                      <div class="alert alert-info alert-block">
                                         <button type="button" class="close" data-dismiss="alert">×</button> 
                                              <strong>{{ $message }}</strong>
                                      </div>
                                      @endif

                                       @if(count($errors))
                                           <div class="alert alert-danger">
                                             <strong>Whoops!</strong> There were some problems with your input.
                                             <br/>
                                             <ul>
                                               @foreach($errors->all() as $error)
                                               <li>{{ $error }}</li>
                                               @endforeach
                                             </ul>
                                           </div>
                                         @endif
                      	                <form action="{{ route('skills.store') }}" method="post">
                      	                	{{ csrf_field() }}
                      	                    <div class="form-body">
                      	                        <div class="row p-t-20">
                      	                            <div class="col-md-12">
                      	                                <div class="form-group">
                      	                                    <label class="control-label">Your Skill</label>
                      	                                    <input type="text" id="name" name="name" class="form-control">
                      	                                </div>
                                                        <div class="form-group">
                                                            <label class="control-label">Skill progress</label>
                                                            <input type="text" id="progress" name="progress" class="form-control">
                                                        </div>
                      	                            </div>
                      	                           
                      	                        </div>
                      	             
                      	                   
                      	                    </div>
                      	                    <div class="form-actions">
                      	                      <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                              <a role="button" class="btn btn-inverse" href="{{ route('skills.index') }}">Cancel</a>  
                      	                        
                      	                    </div>
                      	                </form>

                      	            </div>
                      	        </div>
                      	    </div>
                      		

                      		<div class="col-lg-6">
                      	        <div class="card card-outline-info">
                      	            <div class="card-header">
                      	                <h4 class="m-b-0 text-white">List of Skills</h4>
                      	            </div>
                      	            <div class="card-body">
                                      @if ($message = Session::get('delete'))
                                      <div class="alert alert-danger alert-block">
                                         <button type="button" class="close" data-dismiss="alert">×</button> 
                                              <strong>{{ $message }}</strong>
                                      </div>
                                      @endif
                      	                <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                      <th>#</th>
                                                      <th>Skill</th>
                                                      <th>Progress</th>
                                                      <th>Edit</th>
                                                      <th>Delete</th>
                                                    </tr>
                                                </thead>
                                                @if($skills)
                                                <tbody>
                                                	@foreach($skills as $key=>$skill)
                                                    <tr>
                                                    	<td>{{ ++$key }}</td>
                                                    	<td>{{ $skill->name }}</td>
                                                      <td>{{ $skill->progress }}</td>
                                                    	<td>
                                                    		<a role="button" href="{{ route('skills.edit',['skill' => $skill->id]) }}"><i class="fa fa-edit icon-size"></i></i></a>
                                                    	</td>
                                                      <td>
                                                        <form action="{{ route('skills.destroy',['skill' => $skill->id]) }}" method="post">
                                                          {{ csrf_field() }}{{ method_field('DELETE') }}
                                                          <button role="link" class="fa fa-trash icon-size" type="submit"></button>
                                                        </form>
                                                      </td>
                                                    </tr>   
                                                    @endforeach                                             
                                                </tbody>
                                                @endif
                                            </table>
                                        </div>
                      	            </div>
                      	        </div>
                      	    </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 