routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/', 'HomeController@aboutMe')->name('welcome');

Route::group(['middleware'=>'auth'], function(){
 //   Route::get('admin', function(){
 //   return view ('admin.dashboard');
	// });
   	//Route::resource('admin','AdminController');
   	Route::get('admin','AdminController@index')->name('dashboard');
	Route::resource('admin/abouts','AboutController');
	Route::resource('admin/skills','SkillController');
	Route::resource('admin/educations','EducationController');
	Route::resource('admin/experiences','ExperienceController');
	Route::resource('admin/portfolios','PortfolioController');
	Route::resource('admin/testimonials','TestimonialController');
	Route::resource('admin/contacts','ContactController');
});

Route::get('/', 'FrontController@getComplateResume');
Route::post('/', 'FrontController@saveContact')->name('contacts');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Experience.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Experience extends Model
{
    //
}

app/Http/Controllers/ExperienceController.php
<?php

namespace App\Http\Controllers;

use App\Experience;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ExperienceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $experiences = Experience::all();
        return view('admin.experiences.index',compact(['experiences']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.experiences.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $experience = New Experience;

         $this->validate($request,[
          'company_name' => 'required|max:100',
          'position' => 'required|max:100',
          'star_date' => 'required|max:100',
          'end_date' => 'required|max:100',
        ],[
          'company_name.required' => ' Company name field is required.',
          'company_name.max' => ' Company name may not be greater than 100 characters.',
          'position.required' => ' Position name field is required.',
          'position.max' => ' Position name may not be greater than 100 characters.',
          'star_date.required' => ' Star date field is required.',
          'star_date.max' => ' Star date name may not be greater than 100 characters.',
          'end_date.required' => ' End date field is required.',
          'end_date.max' => ' End date may not be greater than 100 characters.',
        ]);


        $experience->company_name = $request->input('company_name');
        $experience->position = $request->input('position');
        $experience->star_date = $request->input('star_date');
        $experience->end_date = $request->input('end_date');
        $experience->description = strip_tags($request->input('description'));

        Session::flash('success','Experience Successfully Added');

        $experience->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function show(experience $experience)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function edit(experience $experience)
    {
        return view('admin.experiences.edit', compact(['experience']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, experience $experience)
    {
         $this->validate($request,[
          'company_name' => 'required|max:100',
          'position' => 'required|max:100',
          'star_date' => 'required|max:100',
          'end_date' => 'required|max:100',
        ],[
          'company_name.required' => ' Company name field is required.',
          'company_name.max' => ' Company name may not be greater than 100 characters.',
          'position.required' => ' Position name field is required.',
          'position.max' => ' Position name may not be greater than 100 characters.',
          'star_date.required' => ' Star date field is required.',
          'star_date.max' => ' Star date name may not be greater than 100 characters.',
          'end_date.required' => ' End date field is required.',
          'end_date.max' => ' End date may not be greater than 100 characters.',
        ]);

        $experience->company_name = $request->input('company_name');
        $experience->position = $request->input('position');
        $experience->star_date = $request->input('star_date');
        $experience->end_date = $request->input('end_date');
        $experience->description = $request->input('description');

        Session::flash('update','Experience Successfully Updated');

        $experience->save();

        return redirect('admin/experiences');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function destroy(experience $experience)
    {
        $experience->delete();

        Session::flash('delete','Experience Successfully delete');

        return redirect()->back();
    }
}

resources/views/admin/experiences/create.blade.php
@extends('themes.app.pages')

@section('header-scripts')
    <link rel="stylesheet" href="{{ asset('css/lib/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">Add Experience Details</h4>
                    </div>
                    <div class="card-body"> 
                         @if ($message = Session::get('success'))
                        <div class="alert alert-info alert-block">
                           <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if(count($errors))
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <br/>
                                <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('experiences.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-body">
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Comapny Name</label>
                                            <input type="text" id="company_name" name="company_name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Position</label>
                                            <input type="text" id="position" name="position" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Star Date</label>
                                            <input type="date" id="star_date" name="star_date" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">End date</label>
                                            <input type="date" id="end_date" name="end_date" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Description</label>
                                            <textarea class="textarea_editor form-control" rows="15" name="description" style="height:200px"></textarea>
                                        </div>
                                       
                                    </div>
                                   
                                </div>
                        
                           
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                <a role="button" class="btn btn-inverse" href="{{ route('experiences.index') }}">Cancel</a>
                                
                            </div>
                        </form>
                             
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 

@section('script')
    <!--stickey kit -->
    <script src="{{ asset('js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/bootstrap-wysihtml5.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-init.js') }}"></script>
@stop

resources/views/admin/experiences/edit.blade.php
@extends('themes.app.pages')

@section('header-scripts')
  <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
@stop

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">Add Education Details</h4>
                    </div>
                    <div class="card-body"> 
                        @if ($message = Session::get('success'))
                        <div class="alert alert-info alert-block">
                           <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if(count($errors))
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <br/>
                                <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('experiences.update',['experience' => $experience->id]) }}" method="post">
                            {{ csrf_field() }}{{ method_field('PATCH') }}
                            <div class="form-body">
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Comapny Name</label>
                                            <input type="text" id="company_name" name="company_name" class="form-control" value="{{ $experience->company_name  }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Position</label>
                                            <input type="text" id="position" name="position" class="form-control" value="{{ $experience->position }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Star Date</label>
                                            <input type="date" id="star_date" name="star_date" class="form-control" value="{{ $experience->star_date }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">End date</label>
                                            <input type="date" id="end_date" name="end_date" class="form-control" value="{{ $experience->end_date }}">
                                        </div>
                                        <div class="form-group fr-view">
                                            <label class="control-label">Description</label>
                                            <textarea id="description" class="form-control" rows="15" name="description" style="height:200px">{{ $experience->description }}</textarea>
                                        </div>
                                       
                                    </div>
                                   
                                </div>
                        
                           
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Update</button>
                                 <a role="button" class="btn btn-inverse" href="{{ route('experiences.index') }}">Cancel</a>
                            </div>
                        </form>
                             
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 

@section('script')
    <script>
        CKEDITOR.replace('description');
    </script>
@stop

resources/views/admin/experiences/index.blade.php
@extends('themes.app.pages')

@section('content')
  <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                       <h1 class="card-title">Experience
                        
                        <a class="btn btn-primary pull-right" href="{{ route('experiences.create') }}" type="button">Add Experience</a>
                  
                        </h1>                  
                       <div class="clearfix"></div>
                       <hr>
                     <div class="table-responsive">
                       @if ($message = Session::get('delete'))
                            <div class="alert alert-danger alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button> 
                                <strong>{{ $message }}</strong>
                            </div>
                            @endif
                            <table class="table">
                                <thead>
                                    <tr>
                                      <th width="5%">#</th>
                                      <th width="20%">Comapny name</th>
                                      <th width="20%">Position</th>
                                      <th width="20%">Stat Date</th>
                                      <th width="20%">End Date</th>
                                      <th width="5%">Edit</th>
                                      <th width="5%">Delete</th>
                                    </tr>
                                </thead>
                                @if($experiences)
                                <tbody>
                                  @foreach($experiences as $key=>$experience)
                                    <tr>
                                      <td>{{ ++$key }}</td>
                                      <td>{{ $experience->company_name }}</td>
                                      <td>{{ $experience->position }}</td>
                                      <td>{{ $experience->star_date }}</td>
                                      <td>{{ $experience->end_date }}</td>
                                      <td>
                                        <a role="button" href="{{ route('experiences.edit',['experience' => $experience->id]) }}"><i class="fa fa-edit icon-size"></i></i></a>

                                       
                                      </td>
                                      <td>
                                        <form action="{{ route('experiences.destroy',['experience'=>$experience->id]) }}" method="post">
                                          {{ csrf_field() }}{{ method_field('DELETE') }}
                                           <button role="link" class="fa fa-trash icon-size" type="submit"></button>
                                          
                                        </form>
                                      </td>
                                    </tr>   
                                    @endforeach                                             
                                </tbody>
                                @endif
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 