routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/', 'HomeController@aboutMe')->name('welcome');

Route::group(['middleware'=>'auth'], function(){
 //   Route::get('admin', function(){
 //   return view ('admin.dashboard');
	// });
   	//Route::resource('admin','AdminController');
   	Route::get('admin','AdminController@index')->name('dashboard');
	Route::resource('admin/abouts','AboutController');
	Route::resource('admin/skills','SkillController');
	Route::resource('admin/educations','EducationController');
	Route::resource('admin/experiences','ExperienceController');
	Route::resource('admin/portfolios','PortfolioController');
	Route::resource('admin/testimonials','TestimonialController');
	Route::resource('admin/contacts','ContactController');
});

Route::get('/', 'FrontController@getComplateResume');
Route::post('/', 'FrontController@saveContact')->name('contacts');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use App\About;
use App\Skill;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::all();
        return view('admin.abouts.index', compact(['abouts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.abouts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $about = new About;

        $about->designation = $request->input('designation');
        $about->about_me = strip_tags($request->input('about_me'));

        $profileImage = $request->file('profile_image');
        $newProfileImageName = rand() . '.' . $profileImage->getClientOriginalExtension();
        $profileImage->move(public_path("images"),$newProfileImageName);
        $about->profile_image = $newProfileImageName;

        $cv = $request->file('cv');
        $newCVName = rand() . '.' . $cv->getClientOriginalExtension();
        $cv->move(public_path("images"),$newCVName);
        $about->cv = $newCVName;

        $about->address = $request->input('address');
        $about->phone = $request->input('phone');
        $about->email = $request->input('email');
        $about->fb = $request->input('fb');
        $about->tw = $request->input('tw');
        $about->li = $request->input('li');
        $about->google = $request->input('google');
        $about->git = $request->input('git');
        $about->bitbucket = $request->input('bitbucket');
       
        $about->save();

       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function show(About $about)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function edit(About $about)
    {
        return view('admin.abouts.edit', compact(['about']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, About $about)
    {
        $about->designation = $request->input('designation');
        $about->about_me = strip_tags($request->input('about_me'));

        if($request->hasFile('profile_image')){
            $profileImage = $request->file('profile_image');
            if($about->profile_image){
                unlink(public_path('images/'.$about->profile_image));
            }
            $newProfileImageName = rand() . '.' . $profileImage->getClientOriginalExtension();
            $profileImage->move(public_path("images"),$newProfileImageName);
            $about->profile_image = $newProfileImageName;
        }
        if($request->hasFile('cv')){
            $cv = $request->file('cv');
            if($about->cv){
                unlink(public_path('images/'.$about->cv));
            }
            $newCVName = rand() . '.' . $cv->getClientOriginalExtension();
            $cv->move(public_path("images"),$newCVName);
            $about->cv = $newCVName;
        }
        $about->address = $request->input('address');
        $about->phone = $request->input('phone');
        $about->email = $request->input('email');
        $about->fb = $request->input('fb');
        $about->tw = $request->input('tw');
        $about->li = $request->input('li');
        $about->google = $request->input('google');
        $about->git = $request->input('git');
        $about->bitbucket = $request->input('bitbucket');
       
        $about->save();

       return redirect('admin/abouts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy(About $about)
    {
        //
    }
}

resources/views/admin/abouts/create.blade.php
@extends('themes.app.pages')

@section('header-scripts')
	<link rel="stylesheet" href="{{ asset('css/lib/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
	        <div class="col-lg-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">About Me</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('abouts.store') }}" method="post" enctype="multipart/form-data">
                        	{{ csrf_field() }}
                            <div class="form-body">
                                <h3 class="card-title m-t-15">Add Person Info</h3>
                                <hr>
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Designation</label>
                                            <input type="text" name="designation" id="designation" class="form-control" placeholder="Software Engineer...">
                                        </div>
                                    </div>
                                    <!--/span-->
                                    <div class="col-md-12">
                                        <div class="form-group has-danger">
                                            <label class="control-label">About My Profession</label>
                                            <textarea class="textarea_editor form-control" rows="15" name="about_me" placeholder="Enter text ..." style="height:200px"></textarea>
                                        </div>
                                    </div>
                                    <!--/span-->
                                </div>
                                <!--/row-->
                                <div class="row">
                                	<div class="col-md-6">
                                		<div class="form-group">
						           	    	<label for="profile_image">Profile Image</label>
						           	    	<input type="file" id="profile_image" name="profile_image">
						           	  	</div>
						            </div>
						            <div class="col-md-6">      	
						           	  	<div class="form-group">
						           	    	<label for="cv">Upload My Resume</label>
						           	    	<input type="file" id="cv" name="cv">
						           	  	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="address">Address</label>
						           	    	<input type="text" class="form-control" id="address" name="address" placeholder="Address">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="phone">Phone</label>
						           	    	<input type="text" class="form-control" id="phone" name="phone" placeholder="phone">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="email">Email</label>
						           	    	<input type="text" class="form-control" id="email" name="email" placeholder="email">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="fb">FaceBook Link</label>
						           	    	<input type="text" class="form-control" id="fb" name="fb" placeholder="FaceBook Link">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="tw">Twitter Link</label>
						           	    	<input type="text" class="form-control" id="tw" name="tw" placeholder="Twitter Link">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="li">Linkedin Link</label>
						           	    	<input type="text" class="form-control" id="li" name="li" placeholder="Linkedin Link">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="google">Google Link</label>
						           	    	<input type="text" class="form-control" id="google" name="google" placeholder="google">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="git">Github Link</label>
						           	    	<input type="text" class="form-control" id="git" name="git" placeholder="Github Link">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="bitbucket">Bitbucket Link</label>
						           	    	<input type="text" class="form-control" id="bitbucket" name="bitbucket" placeholder="Bitbucket Link">
						           	 	</div>
						           	</div>
                                    
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                 <a role="button" class="btn btn-inverse" href="{{ route('abouts.index') }}">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
		</div>
    </div>
@stop

@section('script')
	<!--stickey kit -->
    <script src="{{ asset('js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/bootstrap-wysihtml5.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-init.js') }}"></script>
@stop

resources/views/admin/abouts/edit.blade.php
@extends('themes.app.pages')

@section('header-scripts')
	<link rel="stylesheet" href="{{ asset('css/lib/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
	        <div class="col-lg-12">
                <div class="card card-outline-primary">
                    <div class="card-header">
                        <h4 class="m-b-0 text-white">About Me</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('abouts.update', ['about' => $about->id]) }}" method="post" enctype="multipart/form-data">
                        	{{ csrf_field() }}{{ method_field('PATCH') }}
                            <div class="form-body">
                                <h3 class="card-title m-t-15">Add Person Info</h3>
                                <hr>
                                <div class="row p-t-20">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Designation</label>
                                            <input type="text" name="designation" id="designation" class="form-control" placeholder="Software Engineer..." value="{{ $about->designation }}">
                                        </div>
                                    </div>
                                    <!--/span-->
                                    <div class="col-md-12">
                                        <div class="form-group has-danger">
                                            <label class="control-label">About My Profession</label>
                                            <textarea class="textarea_editor form-control" rows="15" name="about_me" placeholder="Enter text ..." style="height:200px">{{ $about->about_me }}</textarea>
                                        </div>
                                    </div>
                                    <!--/span-->
                                </div>
                                <!--/row-->
                                <div class="row">
                                	<div class="col-md-6">
                                		<div class="form-group">
						           	    	<label for="profile_image">Profile Image</label><br>
						           	    	<img width="100" height="100" src="/images/{{ $about->profile_image }}" >
						           	    	{{-- <img width="250" height="269" style="border-radius: 50%;" src="{{ asset('public/images/'.$about->profile_image) }}" alt=""/> --}}<br>
						           	    	<input type="file" id="profile_image" name="profile_image">
						           	  	</div>
						            </div>
						            <div class="col-md-6">      	
						           	  	<div class="form-group">
						           	    	<label for="cv">Upload My Resume</label><br>
						           	    	<lable><embed src="/images/{{ $about->cv }}" type="application/pdf" height="100px" width="200px"></lable><br>
						           	    	<input type="file" id="cv" name="cv">
						           	  	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="address">Address</label>
						           	    	<input type="text" class="form-control" id="address" name="address" placeholder="Address" value="{{ $about->address }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="phone">Phone</label>
						           	    	<input type="text" class="form-control" id="phone" name="phone" placeholder="phone" value="{{ $about->phone }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="email">Email</label>
						           	    	<input type="text" class="form-control" id="email" name="email" placeholder="email" value="{{ $about->email }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	  	<div class="form-group">
						           	    	<label for="fb">FaceBook Link</label>
						           	    	<input type="text" class="form-control" id="fb" name="fb" placeholder="FaceBook Link" value="{{ $about->fb }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="tw">Twitter Link</label>
						           	    	<input type="text" class="form-control" id="tw" name="tw" placeholder="Twitter Link" value="{{ $about->tw }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="li">Linkedin Link</label>
						           	    	<input type="text" class="form-control" id="li" name="li" placeholder="Linkedin Link" value="{{ $about->li }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="google">Google Link</label>
						           	    	<input type="text" class="form-control" id="google" name="google" placeholder="google" value="{{ $about->google }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="git">Github Link</label>
						           	    	<input type="text" class="form-control" id="git" name="git" placeholder="Github Link" value="{{ $about->git }}">
						           	 	</div>
						           	</div>
						           	<div class="col-md-6">
						           	 	<div class="form-group">
						           	    	<label for="bitbucket">Bitbucket Link</label>
						           	    	<input type="text" class="form-control" id="bitbucket" name="bitbucket" placeholder="Bitbucket Link" value="{{ $about->bitbucket }}">
						           	 	</div>
						           	</div>
                                    
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Update</button>
                                <a role="button" class="btn btn-inverse" href="{{ route('abouts.index') }}">Cancel</a>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
		</div>
    </div>
@stop

@section('script')
	<!--stickey kit -->
    <script src="{{ asset('js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/bootstrap-wysihtml5.js') }}"></script>
    <script src="{{ asset('js/lib/html5-editor/wysihtml5-init.js') }}"></script>
@stop

resources/views/admin/abouts/index.blade.php
@extends('themes.app.pages')

@section('content')
	<div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                       <h1 class="card-title">About Me 
                        @if(!$abouts)
                        <a class="btn btn-primary pull-right" href="{{ route('abouts.create') }}" type="button">Add MySelf</a>
                        @else
                        @foreach($abouts as $about)
                         <a class="btn btn-primary pull-right" href="{{ route('abouts.edit',['about' => $about->id]) }}" type="button">Update MySelf</a>
                         @endforeach
                        @endif
                        </h1>                  
                       <div class="clearfix"></div>
                       <hr>
                       @foreach($abouts as $about)
                            {!! $about->about_me !!}<br><hr>
                            <span class="col-6 pull-left">
                               <img src="{{ asset('/images/'.$about->profile_image) }}" width="180" height="200">
                               {{-- <img width="250" height="269" style="border-radius: 50%;" src="{{ asset('public/images/'.$about->profile_image) }}" alt=""/> --}}
                            </span>  
                            <span class="col-6">
                                <ul class="list-icons">
                                    <li><b>Address:</b> {{ $about->address }}</li>
                                    <li><b>Phone:</b> {{ $about->phone }}</li>
                                    <li><b>Email:</b> {{ $about->email }}</li>
                                    <li><b>FaceBook Link:</b><a href="{{ $about->fb }}"> {{ $about->fb }} </a></li>
                                    <li><b>Twitter Link:</b><a href="{{ $about->tw }}"> {{ $about->tw }} </a></li>
                                    <li><b>Linkedin Link:</b><a href="{{ $about->li }}"> {{ $about->li }} </a></li>
                                    <li><b>Github Link:</b><a href="{{ $about->git }}"> {{ $about->git }} </a></li>
                                    <li><b>Bitbucket Link:</b><a href="{{ $about->bitbucket }}"> {{ $about->bitbucket }} </a></li>
                                    <li><b>Google+ Link:</b><a href="{{ $about->google }}"> {{ $about->google }} </a></li>
                                   
                                </ul>
                                
                            </span><br><br>

                            <span class="col-12">
                                <embed width="100%" height="600px" src="/images/{{ $about->cv }}" type="application/pdf">
                            </span> 
                                            
                       @endforeach
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
@stop 